### ISSUE TITLE
module specification

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Thermostat_EEM#1]
@jordens 
- Do we need PoE?
- I assume that we can connect all AFEs to the same SPI interface, 4 chips per SPI
- DACs will share same SPI interfaces - two chips per SPI
- do we need individual PWMs for each TEC channel?
- I assume we want a downstream/upsteream EEM channel like in the Stabilizer. Was it tested already?
- what connectors? We can use ribbons with DSUB placed on separate panels as in the original Thermostat. But this takes a lot of space. We can also use HD DSUB and have 2 TECs and 4 sensors in each HDSUB15. In this way, noone will mix them with Thermostat or RS232 :) These days nobody is using VGA.

**Comment by jordens** [comment]
> * Do we need PoE?

Not strictly need it if causes problems. But it fits the power envelope and would play nicely with the rest of the hardware.

> * I assume that we can connect all AFEs to the same SPI interface, 4 chips per SPI

Yes.

> * DACs will share same SPI interfaces - two chips per SPI

Yes.

> * do we need individual PWMs for each TEC channel?

You mean one MAX1968 per TEC? Yes.
Or do you mean the I/V limit PWMs? Those can be banked, let's say two TECs per set of voltages. But let's try to keep them as separate as possible.
But I might be misunderstanding you.

> * I assume we want a downstream/upsteream EEM channel like in the Stabilizer. Was it tested already?

With Stabilizer not that I know of. With Humpback and Urukul yes.
If there are space/pin problems, I'd rather drop the EEM connector but keep PoE.

> * what connectors? We can use ribbons with DSUB placed on separate panels as in the original Thermostat. But this takes a lot of space. We can also use HD DSUB and have 2 TECs and 4 sensors in each HDSUB15. In this way, noone will mix them with Thermostat or RS232 :) These days nobody is using VGA.

I'm only waiting for someone to connect a monitor to a Booster main board ;)

Do you mean [DE-15](https://en.wikipedia.org/wiki/D-subminiature)? Fine with me.
@j-hirsch and FBH should weigh in.

**Comment by gkasprow** [comment]
The pinout could be as follows
![obraz](https://user-images.githubusercontent.com/4325054/95886014-4c2d2700-0d7e-11eb-8939-df634cf8fbde.png)

**Comment by gkasprow** [comment]
It looks like we will have individual PWM channels for all TEC driver settings.

**Comment by gkasprow** [comment]
Initial placement
![obraz](https://user-images.githubusercontent.com/4325054/97494023-14210900-1966-11eb-9e0e-a0bd87bde20f.png)

**Comment by jordens** [comment]
When running one big tec from two channels in parallel, would we connect them on the header board?

**Comment by gkasprow** [comment]
I'm not 100% sure if you can easily run two channels in parallel. These are synchronous converters - even a small differences in duty cycle will result in high cross-current flowing within the pair of shorted outputs. The header board is for debugging purposes.

**Comment by jordens** [comment]
Aren't the drivers effectively current sources which should work in parallel? FBH indicated that they need one case with two in parallel. Best to disuss with @j-hirsch @schiemangk.

**Comment by jordens** [comment]
Alternatively it might be easy to just use two electrically separate half-size TECs to get the same result.

**Comment by hartytp** [comment]
looks nice! Any further thoughts about power management here? Can you get enough juice out of a single EEM for that many TEC drivers?

**Comment by jordens** [comment]
It'll need active power management and load sharing anyway. EEM is probably not going to be the use case for us but the connector/cable is probably not going to be the limitation. It's just there because we can.
