### ISSUE TITLE
MAX1969 option

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#11]
![image](https://user-images.githubusercontent.com/1338946/97970855-72b11180-1dc2-11eb-91f7-fd9431d2becb.png)

We should move the jumper behind the inductors L2 and L4 to utilize them in parallel and C67/C66 as well.

This should be:

* a jumper between the right sides of L4 and L2 (DNP for bipolar)
* a jumper between the right side of L4 and OS2 (DNP for unipolar)
* (done) a jumper from OS2 to GND (DNP for bipolar).

Can we easily make all three jumpers and the CMC capable of 6 A? If not, 5A is also fine.

![image](https://user-images.githubusercontent.com/1338946/97970535-f4ed0600-1dc1-11eb-8cde-e28fb4e49a08.png)
![image](https://user-images.githubusercontent.com/1338946/97970574-03d3b880-1dc2-11eb-9097-6a8d96b9953e.png)

**Comment by gkasprow** [comment]
I replaced the CMC with a[ 1.8uH 9A](https://pl.mouser.com/datasheet/2/336/P850-1527002.pdf) one. Slightly bigger but fits nicely.

**Comment by gkasprow** [comment]
I used dedicated 1206 0.5mR jumpers. Standard 0R 1206 resistors are roughly 50mOhm

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/98159613-30302780-1edd-11eb-9bd5-f0f1aaaa0884.png)
