### ISSUE TITLE
D-44 pinout

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#13]
Feel free to shuffle this for most convenient routing on Thermostat and on the header board. I don't care about the pin ordering.

![image](https://user-images.githubusercontent.com/1338946/97964831-afc4d600-1db9-11eb-9730-d7bf64ea5c89.png)

**Comment by gkasprow** [comment]
I already changed the layout twice to make routing of high current lines easier I will Y-mirror it.
