### ISSUE TITLE
testpoints for MaxCurrentNet/Pos/Voltage

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#14]
Could you move those testpoints behind the reconstruction filter?

![image](https://user-images.githubusercontent.com/1338946/97965242-58733580-1dba-11eb-9a26-c188727963db.png)

**Comment by gkasprow** [comment]
Are U sure?
In the case of DMM, it does not matter, but currently, you can also observe the PWM pattern.

**Comment by jordens** [comment]
Ack
