### ISSUE TITLE
Supply connectors for sensors.

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#16]
If we supply the connectors for the TECs, we should also supply the ones for the sensors.

![image](https://user-images.githubusercontent.com/1338946/97966056-945aca80-1dbb-11eb-95a5-5e355f8ec2a4.png)

**Comment by gkasprow** [comment]
thanks for reminding me. I planned to do so but I forgot :)

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/98135771-83e04800-1ec0-11eb-9ecf-8de13811773e.png)
