### ISSUE TITLE
Fan CPU protection

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#17]
Can we increase R9? ~10 mA still sound like a lot going into the CPU pin. And the fan not working might be noticed pretty late.
![image](https://user-images.githubusercontent.com/1338946/97967156-24e5da80-1dbd-11eb-9bcc-76fd5d4c7e0a.png)

**Comment by gkasprow** [comment]
right. it's probably too low to cause latch-up, but for this frequency, 10k would work as well
