### ISSUE TITLE
Allow EEM/Molex/Barrel 12V to be measured with the shunt

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#18]
These should drive P12V0_R

![image](https://user-images.githubusercontent.com/1338946/97969413-501df900-1dc0-11eb-94ec-648bf53ac55a.png)

**Comment by jordens** [comment]
And the EEM (by default) as well.

![image](https://user-images.githubusercontent.com/1338946/97995651-13192d00-1de7-11eb-8b44-871da5dccbe3.png)

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/98047387-15ea4100-1e2c-11eb-9633-76c7b3b27814.png)
![obraz](https://user-images.githubusercontent.com/4325054/98047406-1da9e580-1e2c-11eb-97bf-35b0b7f7e446.png)
![obraz](https://user-images.githubusercontent.com/4325054/98047544-5ea1fa00-1e2c-11eb-947c-15e116cdca83.png)

The only issue is that the load connected to EEM is not measured.
What we can do is to add yet another FET that would redirect the current when powering downstream port
![obraz](https://user-images.githubusercontent.com/4325054/98047725-b6d8fc00-1e2c-11eb-9ee2-daa7c0bfa63c.png)

**Comment by jordens** [comment]
I don't think that's necessary. But I'll leave it to you.

**Comment by gkasprow** [comment]
let's keep it simple then.
