### ISSUE TITLE
I2C isolation

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#19]
Let's use CPU_RESETn to drive those FETs. It's later than P5V0 and later than P3V3

![image](https://user-images.githubusercontent.com/1338946/97987105-07c00480-1ddb-11eb-8c3a-443f37b0d9a6.png)

**Comment by jordens** [comment]
I'd also place the LM75 on the EEM side of the I2C bus (I2C_SDA/SCL instead of I2C4_SDA/SCL)

![image](https://user-images.githubusercontent.com/1338946/97990737-ad29a700-1de0-11eb-8fa1-b8f8b3c84d88.png)

**Comment by jordens** [comment]
And we need 10k pullups to P3V3_MP on the EEM side of the I2C bus (I2C_SDA/SCL).

**Comment by gkasprow** [comment]
I'd use P5V0A which wakes up as the last one after P3V3. It will result with lower Rdson.

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/98052739-42f02100-1e37-11eb-9c71-419c60ae150e.png)
