### ISSUE TITLE
Unify USB TVS

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#20]
Maybe these can become one BOM line and USB_ID could also be protected for free.

![image](https://user-images.githubusercontent.com/1338946/97992234-b3208780-1de2-11eb-8898-3b90a6a21186.png)

![image](https://user-images.githubusercontent.com/1338946/97992205-a9971f80-1de2-11eb-8be2-ab8092217689.png)

**Comment by gkasprow** [comment]
sure! I did it already in Stabilizer.

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/98047232-e1768500-1e2b-11eb-9948-b27752db6990.png)
