### ISSUE TITLE
board guide keepout

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#21]
We should not put top layer traces into the board guide area. That'll work against metallic enclosure edges and wear of the solder mask. It's also no good for cPCIs IIRC.

![image](https://user-images.githubusercontent.com/1338946/97997824-a8b5bc00-1de9-11eb-8e6d-dce91ca3fc46.png)

**Comment by gkasprow** [comment]
that's not top layer. The trace is on L2. It may look misleading due to prepreg transparency settings:)

**Comment by jordens** [comment]
Ah. Ok then!
