### ISSUE TITLE
D44 assembly

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#23]
With the connectors like this, the two boards have to be separated before soldering the D44 connectors. Breaking on the drill line after soldering probably won't work because you can't bend the connectors when connected. Is this the intention?

![image](https://user-images.githubusercontent.com/1338946/98447006-f9971e80-2121-11eb-874e-910eac197aff.png)

**Comment by gkasprow** [comment]
breaking will be easy
![obraz](https://user-images.githubusercontent.com/4325054/98447106-948ff880-2122-11eb-847d-c7d411b2fb0c.png)

The connectors will be mounted after all, but U are right, they can be also mounted automatically - we have such machine. I will separate them a bit.

**Comment by jordens** [comment]
Yes. I have seen the break line. But that breaks by bending and you can't bend the connectors when mated. So you'd have to make sure that they are mounted after breaking. I don't know how the assembly works and how much is done manually, but it might be easier to allow the board to be broken off after all assembly. That would require separating the boards by more.

**Comment by gkasprow** [comment]
Actually we have a special machine that separates the boards. We don't break them manually.
It's logistically easier to do after automatic soldering. Once you separate them, It's hard to grip it for automatic soldering...

**Comment by jordens** [comment]
Right. As mentioned I thought that you solder before separating. Then I wonder how the machine separates without bending or shearing (which would both stress the mated connectors a lot) and also without direct access to both sides of the drill lines.

**Comment by jordens** [comment]
I guess if it's a saw that does the separation, this is fine.

**Comment by gkasprow** [comment]
I separated the two boards
![obraz](https://user-images.githubusercontent.com/4325054/105088218-e1396d80-5a9b-11eb-8c4a-6bda0046d422.png)
