### ISSUE TITLE
P5V0_AFE as Vexc on the header board

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#24]
Still #4.

* I'd like to have P5V0_AFE to serve as Vexc (pin 8) on the connectors J7,J8,J11,J13, not P3V0_AFE.
* That's why on the header board I'l like more filtering capacitance for P5V0_AFE.
* The P5V0A trace to the D44 connector on the main board should also become a bit thicker (8*10 mA) as should the trace on the header board.

![image](https://user-images.githubusercontent.com/1338946/98447218-56df9f80-2123-11eb-90d4-cd1cddf9bfe6.png)

**Comment by gkasprow** [comment]
Right, 3V3 doesn't make much sense here

**Comment by gkasprow** [comment]
I added FB + 100nF, also routed dedicated 20mils trace directly to the LDO

**Comment by jordens** [comment]
LDO? That should be P5V0_AFE.
The LDO is only for the EEPROM, right?

**Comment by gkasprow** [comment]
Yes, it is only for EEPROM.
