### ISSUE TITLE
CurrentSet needs filtering

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#25]
I think there should be RC filtering on the DAC output since it uses 10 kHz PWM to get the two LSBs. Something like 1 kHz seems good.
We can also just use 16 bits and then there won't be PWM tones.

![image](https://user-images.githubusercontent.com/1338946/98447390-c6a25a00-2124-11eb-9630-303850c05bed.png)

**Comment by gkasprow** [comment]
OK, it was there originally, I forgot why :)

**Comment by gkasprow** [comment]
done 
![obraz](https://user-images.githubusercontent.com/4325054/105075842-9531fd00-5a8a-11eb-979d-6818e6eebb18.png)
