### ISSUE TITLE
AIN4 to GND

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#27]
(Reverses https://github.com/sinara-hw/Thermostat_EEM/issues/3#issuecomment-720581202)

* AIN4 should be connected to GND to measure single ended voltages easily.

I misread the AD7172 datasheet and didn't see the option to use the internal reference independent of what's connected to REF+-. Sorry about the confusion.

![image](https://user-images.githubusercontent.com/1338946/98448126-4ed72e00-212a-11eb-909a-89d605166355.png)

**Comment by gkasprow** [comment]
done 
![obraz](https://user-images.githubusercontent.com/4325054/105078630-936a3880-5a8e-11eb-8f06-595b74d0dec6.png)
