### ISSUE TITLE
P5V0A load

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#28]
I think the R at the P5V0A LDO input needs to go away. ADCs, DACs and the Vexc branches are about (3 + 1 + 20 mA) * 4 ~ 100 mA max. That would bee too much for that 1/16 W resistor.

* Maybe just R105 = 0R? The ADCs and DACs have their own RC filtering already.

![image](https://user-images.githubusercontent.com/1338946/98448872-a3c97300-212f-11eb-8573-34341c6adc31.png)

**Comment by gkasprow** [comment]
we already use 10R 0805 resistors so I will place two in series.
