### ISSUE TITLE
input filter capacitors

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#31]
Let's lower C105, C46, C110, C53, C120, C121 from 100 nF to 10 nF to get a 1kHz corner (10+(10||10) nF and 10||(5+5) k). This is still 120 dB at the first alias. Matches the 1 kHz corner filter after the DAC (https://github.com/sinara-hw/Thermostat_EEM/issues/25).

![image](https://user-images.githubusercontent.com/1338946/98547886-199d1e00-2299-11eb-901b-dc96904778b9.png)

**Comment by gkasprow** [comment]
Do the same in Thermostat as well?

**Comment by gkasprow** [comment]
done

**Comment by filipswit** [comment]
Modified:
![image](https://user-images.githubusercontent.com/24258965/142866254-16643f6e-d18f-47cf-a2a0-4dc7b2a8cbfd.png)
