### ISSUE TITLE
J7,8,11,13 Vrefbx- close to GND

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#34]
Please move Vrefbx- to pin2 close to the GND pin1 on J7/J8/J11/J13.

The pinout from pins 1-8 should be GND, Vrefbx-, SENSBx_2, SENSBx_1, SENSBx_2, SENSBx_1, Vrefbx+, P5V0_AFE.

![image](https://user-images.githubusercontent.com/1338946/98664758-12364d00-234b-11eb-81da-d16a773ac03e.png)

**Comment by gkasprow** [comment]
done 
![obraz](https://user-images.githubusercontent.com/4325054/105087849-653f2580-5a9b-11eb-9ce6-5a0523caea0a.png)

**Comment by jordens** [comment]
Good idea! But then R129 and R130 should be treated the same. They should also move to the header board. and be placed accross pins 8-7 and 1-2 respectively.

And I'm not sure we need this section then anymore:
![image](https://user-images.githubusercontent.com/1338946/105091009-8144c600-5a9f-11eb-9bce-a7f652e5c864.png)

**Comment by gkasprow** [comment]
right!

**Comment by gkasprow** [comment]
done 
![obraz](https://user-images.githubusercontent.com/4325054/105100125-1dc19500-5aad-11eb-8fba-d36d5182a5c2.png)
