### ISSUE TITLE
0805 footprints for reference resistors and wider sense traces

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#35]
Currently the reference resistors dominate the temperature coefficient (an order of magnitude more than ADC gain tempco, lead resistance tempco, lead thermoelectric emf, ADC offset tempco, resistor voltage coefficients).
A fix would be to get better resistors.

Those could in principle be on the (actual) header board. That would also cancel lead resistance tempco and lead resistance offsets/instabilities. Alternatively we could go to 0.2 ppm/C resistors. 5k is available in 0603 (Y16365K00000F0W). But many more resistors are available in 0805 size from 0.2 ppm/C (Y16295K00000T9R) to the existing 5 ppm/C.

* Could we go for 0805 size reference resistors (e.g. TNPU08054K99BZEN00 or better Y16295K00000T9R for R91 R44 R132 R50)? Resistance can be anywhere from 4.7-5.2k.

To stay below the effect of the reference resistor tempco (in the default 2 wire measurement configuration), the traces between the reference resistors and the NTC need to stay below 0.3 Ohm. That's 10 cm of 6x1.38 mil trace max (round trip).

* Could we widen the sense traces (SENS[01]_[PN] net from the reference resistors R91 R44 R132 R50 to the D44 connector and on the breakout board) to 10 mil?

**Comment by gkasprow** [comment]
Sure, let's go.
The most precise ones are in the miniMELF package (1206). We have a lot of space.

**Comment by jordens** [comment]
Are you sure? On digikey, the common SMT resistors around ~5k and 0.2 ppm/K are 0805, some 1206, no miniMELF.

**Comment by gkasprow** [comment]
It used to be the case 15 years ago. It was easier to seal miniMELF. Bit it seems the situation changed recently :)

**Comment by gkasprow** [comment]
Let's go for Y16245K00000T9R. I have them already in my libs.

**Comment by jordens** [comment]
Agreed

**Comment by gkasprow** [comment]
I added them on the header board, the ones close to DACs will be DNP
![obraz](https://user-images.githubusercontent.com/4325054/105083371-17272380-5a95-11eb-9d15-dc346f952cd2.png)
