### ISSUE TITLE
cooling

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Thermostat_EEM#36]
I added optional cooling - it consists of the fan (same model as used in Thermostat) and a piece of PCB or metal plate.
The mounting plate distributes the airflow between the channels. The inductors form the air duct so that should work. 
![obraz](https://user-images.githubusercontent.com/4325054/105031256-59307500-5a55-11eb-970c-ae154de57040.png)

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/105063162-b4755e00-5a7b-11eb-9d50-6c14735b3d90.png)

**Comment by jordens** [comment]
Maybe that's also a useful approach for (https://github.com/sinara-hw/Phaser/issues/101#issuecomment-682044877)

**Comment by gkasprow** [comment]
The mounting holes will fit.
