### ISSUE TITLE
Move R129 and R130 to the header board.

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#38]
Good idea in #34! But then R129 and R130 should be treated the same.

![image](https://user-images.githubusercontent.com/1338946/105092961-47c18a00-5aa2-11eb-9896-96fab9b9af59.png)
![image](https://user-images.githubusercontent.com/1338946/105092995-5314b580-5aa2-11eb-9c28-f4b910829985.png)

They should also move to the header board. and be placed accross pins 8-7 and 1-2 respectively.

And I'm not sure we need this section then anymore:
![image](https://user-images.githubusercontent.com/1338946/105091009-8144c600-5a9f-11eb-9bce-a7f652e5c864.png)

_Originally posted by @jordens in https://github.com/sinara-hw/Thermostat_EEM/issues/34#issuecomment-763129398_

**Comment by gkasprow** [comment]
I moved them and made that section DNP

**Comment by jordens** [comment]
Perfect
