### ISSUE TITLE
P5V0A as Vexc on the header board

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#4]
![image](https://user-images.githubusercontent.com/1338946/97962730-0fb97d80-1db6-11eb-946e-5555355c8325.png)

Not P3V3_AFE.

Also maybe add (a ferrite bead and) 100 n decap to P5V0A on the header board.

**Comment by jordens** [comment]
And I think we may want to add a polyfuse on Thermostat towards the D44 connector P5V0A.

**Comment by gkasprow** [comment]
This comes from 300mA LDO. I'm not sure if it's worth adding PTC to BOM

**Comment by jordens** [comment]
Right. I guess the LDO will just shut down.

**Comment by gkasprow** [comment]
yes, it will get thermal shutdown.

**Comment by gkasprow** [comment]
on the header board, we have 33Ohm series resistor already

**Comment by jordens** [comment]
That's for the P3V3_AFE LDO, right? For the excitation voltage to the sensor connectors I'd like P5V0A with no large added resistance, just some filtering. (e.g. load cells are just a couple hundred Ohm only and like to pull > 10 mA at 5 V.)
