### ISSUE TITLE
P5V0A protection zener

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#40]
Let's go for the slightly higher zener protection diode here. 1SMA5920BT3G, 6.2 V instead of 5.6 V.
The ADC has 6.5 V abs max and the CPU side is powered by an independent 3V3 supply.

![image](https://user-images.githubusercontent.com/1338946/106788967-f0025180-6651-11eb-87d4-122755ac29e7.png)

In light of previous experience.

**Comment by gkasprow** [comment]
done
