### ISSUE TITLE
ADC_DOUT/RDY to SPI_MISO and EXTI

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#45]
It's useful to interrupt when the ADC is ready instead of polling. For that it's nice if we can use an EXTI interrupt from a GPIO input pin concurrently with SPI. Then we don't have to reconfigure the single pin between SPI and GPIO all the time and don't run into software issues when doing so.

We should connect ADC_DOUT/RDY to both SPI_MISO (PE5 as currently) and some other pin for EXTI usage (e.g. PC11 currently unused).

![image](https://user-images.githubusercontent.com/1338946/138117681-da2d5e69-6765-40f0-b92d-8cfb33d2c2fe.png)

**Comment by filipswit** [comment]
Connected PC11 RDYn to ADC_DOUT/RDyn through 0R jumper:
![image](https://user-images.githubusercontent.com/24258965/142867659-e5a7db9f-0ad0-4998-892d-310f3abf9389.png)
