### ISSUE TITLE
RC filter on CPU ADC channels (ITEC)

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#46]
Let's make them all 10k/10n for 1.6 kHz bandwidth.

Add a RC filter with the usual 10k/10n combo on ITEC on all 4 TEC channels.

![image](https://user-images.githubusercontent.com/1338946/138120657-0bfa3f82-55e1-4e73-af91-eb5d4681f153.png)

Maybe (?) add a 10k/10n RC on the VREF signal to the CPU ADCs on all 4 TEC channels

![image](https://user-images.githubusercontent.com/1338946/138121694-462dbeb5-f883-4bbd-80f9-4652f2f9326d.png)

Increase the RC on the TEC_U_meas signal to 10k/10n on all 4 TEC channels

![image](https://user-images.githubusercontent.com/1338946/138121161-41cf9b4d-c658-4877-813e-d86fbd0b1615.png)

Lower the RC on I_MEAS_12V to 10k/10n

![image](https://user-images.githubusercontent.com/1338946/138121287-12ed8d31-0c05-44c1-9c73-2acbe8293c96.png)

**Comment by filipswit** [comment]
Added 10k/10n to ITEC and Vref
![image](https://user-images.githubusercontent.com/24258965/142867934-0bb489a9-a31c-4844-ac9f-06e3467d4e16.png)

Increased TEC_U_meas to 10k/10n
![image](https://user-images.githubusercontent.com/24258965/142868003-9b93f8e8-2c14-406a-af0e-0dc35bc2fd6a.png)

Decreased I_meas_P12V0 to 10k/10n
![image](https://user-images.githubusercontent.com/24258965/142868098-f3829fff-1184-4301-a44b-23f52c684f90.png)
