### ISSUE TITLE
cable on BOM

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#47]
I can't find the fan, the fan board, and the mounting hardware (8 screws, washers, 4 spacers) on the schematics. Let's make sure they are included in the BOM for the board.
Also let's try to get the cable into the BOM if there is the test AFE in it.
I see that you have a suitable cable link on the schematic already.

**Comment by gkasprow** [comment]
The spacers are SMT-mounted ones (S1..S4), screws are there on the top entity page (SCREW1...4).
Fan board is here
https://github.com/sinara-hw/Thermostat_EEM/tree/master/Fan_board_Thermostat%208CH
the fan and mounting HW is here
![obraz](https://user-images.githubusercontent.com/4325054/138354028-bd32bbd2-b448-4249-a9b1-b4fb3f28308b.png)
