### ISSUE TITLE
Stock problems v1.0

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Thermostat_EEM#48]
Due to stock problems: 

- Alternate power supply section has been added. 
![image](https://user-images.githubusercontent.com/24258965/143488351-f128da81-fd14-4ab4-b6f5-b69923738896.png)

- Indicator leds are 4x green instead of 2x green and 2x red
- ARJM11C7-114-BA-EW2 changed to 2337992-8

**Comment by jordens** [comment]
That's a 6 A limit now. A bit small compared to the 14 A of the MIC. It would be good if we can at least make 8 A, better 12 A (3 A per TEC not including losses). We have a high power 12 V connection that can supply enough. I'd rather not be limited by the 5 V power supply.

**Comment by filipswit** [comment]
It's hard to find something what is small enough, high current and it's possible to buy in this year.

**Comment by jordens** [comment]
If this is an emergency alternative, OK. Can we make the boards so that they can be upgraded to the MIC by rework when available?

**Comment by akaminska** [comment]
@jordens this is only a temporary solution for the purpose of the prototype series, in order to be able to manufacture it now. If you think that it will be really useful, we can try to squeeze in one more 584-LTM4623EV#PBF

**Comment by filipswit** [comment]
@jordens We treat LTM4623 as temporary solution. MIC section is left as it was, we would like to mount all RC components and as soon as MIC will be available, upgrade will be possible. 

![image](https://user-images.githubusercontent.com/24258965/143243289-221ad5e1-39c9-4fb6-ad7c-28b5db3b7c99.png)

**Comment by filipswit** [comment]
@jordens finally i squeezed there 3rd DC/DC so now we have 3x3A.
