### ISSUE TITLE
Fan board issues

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Thermostat_EEM#49]
- [x] screws should be 14mm instead of 12mm
- [x] pcb should be at least 1.4mm thick
- [x] missing fan connector

**Comment by gkasprow** [comment]
@filipswit what do you mean by missing fan connector?

**Comment by gkasprow** [comment]
what's wrong with 12mm screws?

**Comment by filipswit** [comment]
- Fan connector should be added to BoM (Mating to Molex 22-27-2031)
- AFFAIR 12mm screws were barely touching the thread

**Comment by gkasprow** [comment]
Screw replaced with KRAFTBERG_M2.5X14/D7985-A2
Added connector 22012031 and KK contacts 08-52-0125
Thickness is standard 1.6mm
