### ISSUE TITLE
Ethernet PHY can only negotiate 10BASE-T link

### ISSUE THREAD

**Issue by nkrackow** [sinara-hw/Thermostat_EEM#51]
The lan8742 PHY is not able to negotiate a 100BASE-TX connection with the other side of the Link. 

This was tried with 2 different ~1m RJ45 cables (One is Cat.5E) and 3 different USB-Ehernet adapters. With one of the adapters it does not work at all, with the other two the link status glitches between on and off for about 10 sec until the link stabilizes to on with a 10BASE-T connection (which is determined by reading the PHY status regs).
The cables don't make a difference and all adapters and cables work instantly with Stabilizer.

The only difference to Stabilizer in the schematic are these 33 ohm inline resistors:
![Screenshot from 2022-02-02 21-45-48](https://user-images.githubusercontent.com/17088194/152352950-7d2ade00-8cca-40a9-ac5b-e14d3f4c4703.png)

In the layout the traces are much longer.

**Comment by gkasprow** [comment]
The thermostat (2 channel version) is using the same resistors. I didn't check what speed it negotiates though.

**Comment by SingularitySurfer** [comment]
Just checked, it negotiates 100Mbit and also instantly connects.

The problem is that the drivers we are using only support 100BASE-TX full-duplex..

**Comment by jordens** [comment]
@SingularitySurfer quickly check that the ESD array footprint, schematic, and datasheet actually match. There were problems with that before.

**Comment by gkasprow** [comment]
which revision of the Thermostat do you have? these resistors were added quite recently.

**Comment by SingularitySurfer** [comment]
I've got Thermostat v2.0 and Thermostat-EEM v1.0.

ESD array footprint, schematic, and datasheet are the same for both Thermostats and Stabilizer.

**Comment by SingularitySurfer** [comment]
The resistors are not present in Thermostat v2.0 I think.

**Comment by gkasprow** [comment]
right. They were added in v2.1

**Comment by SingularitySurfer** [comment]
Unfortunately I think I ESD-damaged my PHY while bridging the resistors. I'll try swapping the PHY and bridging the resistors tomorrow.

**Comment by jordens** [comment]
@gkasprow where does the 33R series come from, was it a guess to add some more ESD robustness or is that a proven design?
The [phy schematic checklist](https://ww1.microchip.com/downloads/en/DeviceDoc/LAN8742A%20QFN%20Rev%20A%20Schematic%20Checklist.pdf) doesn't have them. But it also doesn't have the ESD diodes so it's of limited value.

**Comment by gkasprow** [comment]
It was recommended in PoE app note to prevent PHY from dying

**Comment by jordens** [comment]
The one you referenced [here](https://github.com/sinara-hw/Thermostat/issues/83#issuecomment-719920167) talks about 0-5 R.
But for that short cable that @SingularitySurfer I wouldn't expect it to make a difference.

**Comment by gkasprow** [comment]
you can short them and see if that makes any difference. So far nobody complained about Thermostat...

**Comment by SingularitySurfer** [comment]
Turns out I ESD damaged the ESD protection diode array such that there appeared another diode to from the data lines to ground..

**Comment by SingularitySurfer** [comment]
With a new PHY, no ESD protection diode array and shorted resistors I instantly get a 100BASE-TX connection.

**Comment by gkasprow** [comment]
the ESD diodes must be there. Otherwise after plugging PoE you will damage PHY instantly,

**Comment by gkasprow** [comment]
you can "borrow" the ESD array from the I2C circuit close to EEM connector (D17)

**Comment by SingularitySurfer** [comment]
Since I don't use PoE I don't need the diode array right now. Would you like me to check if the diode array in there makes a difference? I don't think that's so likely since it's also there on other devices where it works.

**Comment by gkasprow** [comment]
these TVS arrays have very low capacitance and are used in Stabilizer already.
The only thing that changed are these resistors. So I think they caused the problem.
Can you solder 5R1 and see if it works with a long cable?
The traces don't matter, they are still relatively short.

**Comment by SingularitySurfer** [comment]
I neither have resistors that small in physical size, nor any resistor < 10 ohms here..

**Comment by SingularitySurfer** [comment]
Oh and actually since Thermostat has a different MCU it could be that the drivers there support 10Mbit ethernet.

**Comment by gkasprow** [comment]
Isn't the RUST stack the same?

**Comment by SingularitySurfer** [comment]
No, it uses a different HAL and ethernet driver. Unf I can't find it in the m-labs code right now but [here](https://github.com/stm32-rs/stm32-eth/blob/f246fae1dd37d3d20b07e84b4baaa71826388139/examples/arp.rs#L178-L185) they use the same driver a the m-labs code uses to look for any connection in the link, incl. 10Mbit. Not sure if it would work with 10Mbit after that tho.

**Comment by gkasprow** [comment]
OK, that's why nobody noticed the difference

**Comment by SingularitySurfer** [comment]
@jordens We don't have a new Thermostat here right?

**Comment by jordens** [comment]
Not newer than what you have been playing with.

**Comment by SingularitySurfer** [comment]
Some more remarks on the ESD array:
- Between Stabilizer and Thermostat-EEM I have noticed that the schematic symbol, BOM part and footprint name are exactly the same. 
- The actual physical footprint seems to be slightly different with a bigger clearance between solder mask and pad on Thermostat.
- The diode array place on the actual board is not [the one in the BOM](https://octopart.com/datasheet/drtr5v0u4s-7-diodes+inc.-30954912). The marking is TG5, whereas it should be TG1 according to the BOM part. Other ESD arrays on Thermostat have the same TG5 marking.  A Stabilizer v1.2 I could look at has the TG1 marking. Unf. I was not able to find the corresponding datasheet for the TG5 marking, since I cannot search for the marking and the datasheets I could find had other markings.

It is therefore still possible that the diode array makes a difference.

**Comment by jordens** [comment]
https://www.mouser.com/datasheet/2/115/DRTR5V0U4SL-476981.pdf Note the completely different pinout.

**Comment by jordens** [comment]
@SingularitySurfer If this pans out, take home message for you is [check things](https://github.com/sinara-hw/Thermostat_EEM/issues/51#issuecomment-1029065804) first.

**Comment by gkasprow** [comment]
There should be mounted DRTR5V0U4S-7 which has the correct layout. Essential is that pin 5 must have all cathodes connected to it.

**Comment by jordens** [comment]
@gkasprow According to the marking it would be DRTR5V0U4S**L** with the different pinout. Maybe a chance to visit manufacturing and straighten them out ;)

**Comment by gkasprow** [comment]
I wrote them an email. Hope they didn't assemble it in other modules.

**Comment by jordens** [comment]
Anyway, no harm done. Then also no indication of ESD damage, just "undesired diodes". Good that we figured it out. Thanks all!

**Comment by gkasprow** [comment]
OK. Production people assembled DRTR5V0U4SL-7 because one of the engineers told them that it's the same part.

**Comment by jordens** [comment]
All the way to the name of the engineer! ;)

**Comment by gkasprow** [comment]
The other TVS are also bad: D3, D4, D27, D35, D36

**Comment by jordens** [comment]
Maybe also on other Thermostat and Stabilizer builds.

**Comment by SingularitySurfer** [comment]
Hi @gkasprow, we have noticed that diode arrays D21 (USB) and D26 (JTAG) are different arrays with the marking "TV8" and obviously seem to work as intended in case of the JTAG. In the BOM they are the same part as the affected diodes. How come these two are different?

**Comment by jordens** [comment]
Ah. USB may be 5V, too close to the Zener voltage of the TVS.
Maybe JTAG can/could do higher voltage as well. Hence those should be different parts than the others?

**Comment by filipswit** [comment]
To clarify, this are mounted diodes:
D3, D4, D27, D35, D36 - DRTR5V0U4SL-7
D21, D26 - D5V0F4U6S-7

**Comment by jordens** [comment]
Production issue, not a design issue. Nothing to be done.
