### ISSUE TITLE
Testpoints on one TEC/PWM channel soldered

### ISSUE THREAD

**Issue by nkrackow** [sinara-hw/Thermostat_EEM#54]
Small nit: The testpoints on one of the DAC/PWM output channels have solder bumps on them which is likely unintentional makes probing a bit more difficult.
![photo1645453937](https://user-images.githubusercontent.com/17088194/154975587-d3388108-a8b6-4ab9-824b-8ec491dddad3.jpeg)

**Comment by jordens** [comment]
#50 (second point) already tracks this I think
