### ISSUE TITLE
TEC Driver REF pin loading and capacitance

### ISSUE THREAD

**Issue by nkrackow** [sinara-hw/Thermostat_EEM#55]
The TEC Driver IC has a Reference pin that outputs the internal reference voltage. This pin should have a 1uF capacitor according to the datasheet, Thermostat curretly has a 10nF. 
The pin can sink 1mA but only source 10uA. With the current loading the pin is pulled from nominal 1.5V to ~1.05V.
![Screenshot from 2022-02-21 16-38-08](https://user-images.githubusercontent.com/17088194/154987548-54e59faa-0ebe-4d94-93b4-e36b5a9fdf57.png)

**Comment by jordens** [comment]
This was a bug from https://github.com/sinara-hw/Thermostat_EEM/issues/46
I meant adding an 10k R 10n C filter to VREF, after the 1u C and not replacing the 1u with a 10n C and adding an R 10k. That doesn't work.

**Comment by jordens** [comment]
Still, there seems to be something loading it. @SingularitySurfer sure you measured the 1.05V on the pin 4 side or R224?
In any case the voltage divider at IC14 is broken due to the non-zero impedance of R224.

**Comment by SingularitySurfer** [comment]
> Still, there seems to be something loading it. @SingularitySurfer sure you measured the 1.05V on the pin 4 side or R224? In any case the voltage divider at IC14 is broken due to the non-zero impedance of R224.

Actually I measured on the wrong side of the resistor, sorry! The highlighted net on the pin has 1.5V. Behind R224 there is 1.05V left.
![Screenshot from 2022-02-22 10-35-43](https://user-images.githubusercontent.com/17088194/155104582-5437c78e-b65a-444f-a893-a89ef5d2a1c2.png)

**Comment by jordens** [comment]
Ok. Then it's just the divider. And the RC. Should fix both.

**Comment by gkasprow** [comment]
R224=0R, C168=1uF

**Comment by jordens** [comment]
@gkasprow I think that's too much load. VREF can do +10µA to -1mA. We are loading it with 25k from 4.3V worst case (see IC14).

**Comment by gkasprow** [comment]
Right. So let's add another opamp to buffer it. It can be one for all four channels

**Comment by gkasprow** [comment]
Or, let's replace IC14 with LM358

**Comment by gkasprow** [comment]
![image](https://user-images.githubusercontent.com/4325054/223231800-d6a1fe39-f5e4-48d4-984a-b10a5a4cf008.png)

**Comment by jordens** [comment]
The buffer should also drive the other vref users, e.g. to the CPU.

**Comment by gkasprow** [comment]
Fixed in v1.1rc2
