### ISSUE TITLE
CPU debug header very close to the side of the board

### ISSUE THREAD

**Issue by nkrackow** [sinara-hw/Thermostat_EEM#57]
The CPU debug header of Thermostat-EEM collides with the rails when inserting it into some standard, Eurocard sized enclosures. 

However, it doesn't collide with the rails of the standard 19" chassis we use for Sinara systems.

![c6145ca2-7adb-4234-a66c-f0c47e11f91b](https://user-images.githubusercontent.com/17088194/182605252-33e27857-2b77-43b1-86bf-bbd2f6f30270.jpg)

**Comment by gkasprow** [comment]
The original distance was 3.5mm from the board edge to the pin centre. Now is 4.25mm
