### ISSUE TITLE
Add mounting holes on break out boards

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat_EEM#67]
Four standard mounting holes in convenient locations would help a lot. Even though they are meant for experimenting and proper solutions use application-specific AFEs, the standard break out boards tend to be used quite a lot.

**Comment by filipswit** [comment]
Both PCBs extended by 6mm and added four 3,2mm holes:

![image](https://github.com/user-attachments/assets/8e263183-0adc-4ef4-965c-c2d78b593fae)

![image](https://github.com/user-attachments/assets/593c7e2c-637e-43e5-bb62-ba13943c9eb4)
